# Generated by Django 5.1.4 on 2025-01-01 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место для выполения привычки",
                        max_length=100,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время для выполения привычки",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие, которое представляет собой привычка",
                        max_length=200,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        help_text="Укажите, является ли привычка приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.SmallIntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения привычки",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение после выполнения привычки",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_complete",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите продолжительность выполнения привычки",
                        null=True,
                        verbose_name="Продолжительность выполнения",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        help_text="Укажите, необходимо ли публикация",
                        verbose_name="Признак публикации",
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["action", "periodicity", "is_published"],
            },
        ),
    ]
